import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { SiteBreadcrumbsPixel } from "@/components/site-breadcrumbs-pixel";
import { cn } from "@/lib/utils";

/**
 * Font weights for Tailwind classes:
 * font-thin: 100
 * font-extralight: 200
 * font-light: 300
 * font-normal: 400
 * font-medium: 500
 * font-semibold: 600
 * font-bold: 700
 * font-extrabold: 800
 * font-black: 900
 */

const ibmPlexSans = IBM_Plex_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-sans",
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["500", "600"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
});

const pixolletta = localFont({
  src: "./fonts/Pixolletta8px.ttf",
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-pixolleta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        ibmPlexSans.variable,
        ibmPlexMono.variable,
        pixolletta.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <header className="p-4">
          {/* <div className="mx-auto flex h-12 w-full max-w-3xl items-center px-6">
            <SiteBreadcrumbsPixel />
          </div> */}
          <SiteBreadcrumbsPixel className="font-pixel text-base" />
        </header>
        {children}
      </body>
    </html>
  );
}
